### ISSUE TITLE
Test issue 4

### ISSUE THREAD

**Issue by egmar** [egmar/muni-project-one#4]
SSUE TYPE

    Bug Report

SUMMARY

inventory: an ec2 inventory of 12 hosts
playbook that "pushes" an ansible inventory into the API:

```
- hosts: all
  gather_facts: False
  collections:
  - awx.awx

  tasks:
  - name: Create inventory
    tower_inventory:
      name: "{{ inventory_name }}"
      description: "{{ inventory_description | default(omit) }}"
      organization: "{{ organization }}"
      state: present
    run_once: true
    delegate_to: localhost

  - name: Create hosts
    tower_host:
       name: "{{ inventory_hostname }}"
       inventory: "{{ inventory_name }}"
       enabled: true
       variables: "{{ hostvars[inventory_hostname] }}"
       state: present
    delegate_to: localhost

  - name: Create groups
    tower_group:
       name: "{{ item }}"
       inventory: "{{ inventory_name }}"
       hosts: "{{ groups[item] }}"
       state: present
    delegate_to: localhost
    loop: "{{ group_names }}"
```

Timing of playbook:

    to process inventory, create inventory, create hosts: ~30 seconds
    to create groups: 7+ additional minutes

ENVIRONMENT

    AWX version: 10.0.0
